basePath: /v1
host: localhost:8080
info:
  contact: {}
  description: Swagger definitions for axosec vault http api
  title: Axosec vault API
  version: 0.1.0
paths:
  /health:
    get:
      description: returns ok if api up
      responses:
        "200":
          description: OK
      summary: Helthcheck
swagger: "2.0"
